export enum IpcChannel {
  GetStats = 'stats:get',
  GetProjects = 'projects:get',
  GetDataSource = 'data-source:get',
  SetDataSource = 'data-source:set',
  ExportData = 'data:export',
  ImportData = 'data:import',
  ClearImport = 'data:clear-import',
  GetCostAnalysis = 'costs:get',
  GetClaudeSettings = 'settings:get',
  GetSkills = 'skills:get',
  LiveGetActiveAgents = 'live:get-active-agents',
  LiveStartWatching = 'live:start-watching',
  LiveStopWatching = 'live:stop-watching',
  GetCharacterSprites = 'assets:get-character-sprites',
  GetWallSprites = 'assets:get-wall-sprites',
}
